codecov:
  notify:
    after_n_builds: 3

coverage:
  status:
    project:
      default:
        target: auto
      linux:
        flags:
          - linux
      macos:
        flags:
          - macos
      windows:
        flags:
          - windows

flags:
  linux:
    carryforward: true
  macos:
    carryforward: true
  windows:
    carryforward: true
